
services:
  postgres:
    image: postgres:15-alpine
    container_name: secwin_postgres
    environment:
      POSTGRES_USER: secwin_user
      POSTGRES_PASSWORD: secwin_password
      POSTGRES_DB: secwin_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
