services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: secwin_postgres
    environment:
      POSTGRES_USER: secwin_user
      POSTGRES_PASSWORD: secwin_password
      POSTGRES_DB: secwin_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - secwin_network

  # Backend API
  backend:
    build: .
    container_name: secwin_backend
    environment:
      NODE_ENV: production
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: secwin_db
      DB_USER: secwin_user
      DB_PASSWORD: secwin_password
      PORT: 3500
      DOCKER_ENV: true
      SIGNATURES_PATH: /app/signatures
      UPLOADS_PATH: /app/uploads
      SIGNED_DIR: /app/signed
      TEMP_DIR: /app/temp
    volumes:
      - ./uploads:/app/uploads
      - ./signed:/app/signed
      - ./temp:/app/temp
      - ./signatures:/app/signatures
    ports:
      - "3500:3500"
    depends_on:
      - postgres
    networks:
      - secwin_network
    restart: unless-stopped

volumes:
  postgres_data:
  signatures:
  uploads:
  signed:
  temp:

networks:
  secwin_network:
    driver: bridge
